#
# Hello there, user
# this configuration file contains your credentials, make sure not to share it with ANYONE.
# anyone with your Discord private key can controll your bot!
#

# false for light theme
# true  for dark  theme
dark_theme: false

recaptcha:
  # put your public recaptcha key here!
  public: 6LdSjzsdAAAAAGghQsVEiSejFVm3AmmXS-4Lo2Gk
  
  # DO NOT LEAK THIS
  private: 6LdSjzsdAAAAAJi7n7M4KG3Hhqcc0pIaVexXx75x

discord:
  # users will be invited to this room, it should be public
  welcome_room: 910523584416452700

  # DO NOT LEAK THIS
  private: ODQ5Mjk5NzM2ODMzMTYzMjk0.YLZKBA.xKpuYsBLthuvKPjzqVbvbo3ywQk

server:
  # the script will host the gateway on this port
  # defaults to 80
  port: 80