#
# Hello there, user
# this configuration file contains your credentials, make sure not to share it with ANYONE.
# anyone with your Discord private key can controll your bot!
#

# false for light theme
# true  for dark  theme
dark_theme: false

recaptcha:
  # put your public recaptcha key here!
  public: 
  
  # DO NOT LEAK THIS
  private: 

discord:
  # users will be invited to this room, it should be public
  welcome_room: 

  # DO NOT LEAK THIS
  private: 

server:
  # the script will host the gateway on this port
  # defaults to 80
  port: 80